spring: 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: UserService
          uri: lb://UserMS
          predicates:
            - Path=/user/**
        - id: FlightService
          uri: lb://FlightMS
          predicates:
            - Path=/flights/**
        - id: BookingService
          uri: lb://BookingMS
          predicates:
            - Path=/booking/**